apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hb2eyhxmd-python 
  janus-idp.io/tekton: hb2eyhxmd-python
  backstage.io/kubernetes-id: hb2eyhxmd-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hb2eyhxmd-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml