apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hb2eyhxmd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hb2eyhxmd-python 
  name: hb2eyhxmd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hb2eyhxmd-python 
